name: workshop-202511
channels:
- conda-forge
dependencies:
- python==3.12
- pip
- numpy
- pandas>=2
- netcdf4
- pypsa>=1.0
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl
- libgdal-hdf5
- libgdal-netcdf
- cartopy>=0.22
- matplotlib>=3.6
- plotly
- ipython
- jupyterlab
- jupyter-book
- ghp-import
- pre-commit
- geopandas
- shapely
- requests
- pip:
  - highspy
