name: deploy

permissions:
  contents: write

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies

    - name: Install environment with pip
      run: pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build pypsa-workshop-202511

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: pypsa-workshop-202511/_build/html
